# Generated by Django 5.1.4 on 2026-09-09 21:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_alter_profile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, help_text='Internal / donor reference, e.g. GCP/ZAM/123', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('funder', models.CharField(blank=True, help_text='e.g. FAO, EU, USAID', max_length=255)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('closed', 'Closed'), ('suspended', 'Suspended')], default='planning', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('target_provinces', models.JSONField(default=list)),
                ('target_districts', models.JSONField(default=list)),
                ('target_enterprise_categories', models.JSONField(default=list)),
                ('target_farms', models.PositiveIntegerField(default=0, help_text='Enrolment target')),
                ('indicators', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='The partner organisation running the programme', on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='accounts.organization')),
            ],
            options={
                'db_table': 'partner_programmes',
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IndicatorReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('indicator_key', models.CharField(max_length=60)),
                ('period', models.DateField(help_text='Reporting period end date')),
                ('value', models.DecimalField(decimal_places=2, max_digits=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='partners.programme')),
            ],
            options={
                'db_table': 'partner_indicator_readings',
                'ordering': ['indicator_key', '-period'],
            },
        ),
        migrations.CreateModel(
            name='ProgrammeSupport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('support_type', models.CharField(choices=[('input_voucher', 'Input Voucher'), ('seed', 'Seed / Seedlings'), ('fertiliser', 'Fertiliser'), ('livestock', 'Livestock / Fingerlings / Chicks'), ('equipment', 'Equipment / Tools'), ('cash_grant', 'Cash Grant'), ('training', 'Training'), ('extension', 'Extension Service'), ('market_link', 'Market Linkage'), ('other', 'Other')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('value', models.DecimalField(decimal_places=2, default=0, help_text='Monetary value', max_digits=14)),
                ('currency', models.CharField(default='ZMW', max_length=10)),
                ('delivered_on', models.DateField()),
                ('reference', models.CharField(blank=True, help_text='Voucher / GRN / receipt number', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programme_support', to='accounts.organization')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support', to='partners.programme')),
            ],
            options={
                'db_table': 'partner_support',
                'ordering': ['-delivered_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgrammeEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('withdrawn', 'Withdrawn')], default='active', max_length=20)),
                ('cohort', models.CharField(blank=True, help_text='e.g. 2026 Season A, Camp 3', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('enrolled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programme_enrollments', to='accounts.organization')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='partners.programme')),
            ],
            options={
                'db_table': 'partner_enrollments',
                'ordering': ['-enrolled_at'],
                'unique_together': {('programme', 'farm')},
            },
        ),
    ]
