# Generated by Django 5.1.4 on 2026-09-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='target_participant_types',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='programme',
            name='target_farms',
            field=models.PositiveIntegerField(default=0, help_text='Enrolment target (participants)'),
        ),
        migrations.AlterField(
            model_name='programmesupport',
            name='support_type',
            field=models.CharField(choices=[('input_voucher', 'Input Voucher'), ('seed', 'Seed / Seedlings'), ('fertiliser', 'Fertiliser'), ('livestock', 'Livestock / Fingerlings / Chicks'), ('equipment', 'Equipment / Tools'), ('cash_grant', 'Cash Grant'), ('training', 'Training'), ('extension', 'Extension Service'), ('market_link', 'Market Linkage'), ('working_capital', 'Working Capital / Grant'), ('certification', 'Certification Support'), ('digital_tools', 'Digital Tools / Devices'), ('cold_chain', 'Cold Chain / Storage'), ('other', 'Other')], max_length=20),
        ),
    ]
