# Generated by Django 5.1.4 on 2026-09-11 09:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_programme_target_participant_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorreading',
            name='disaggregation',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=60)),
                ('label', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, max_length=40)),
                ('baseline', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('baseline_date', models.DateField(blank=True, null=True)),
                ('target', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('means_of_verification', models.CharField(blank=True, max_length=255)),
                ('data_source', models.CharField(blank=True, max_length=255)),
                ('disaggregations', models.JSONField(default=list, help_text='subset of sex / age / participant_type / district')),
                ('auto_source', models.CharField(blank=True, choices=[('', 'Manual readings'), ('participants_enrolled', 'Participants enrolled (active)'), ('participants_women', 'Women-headed participants'), ('participants_youth', 'Youth-headed participants (≤ 35)'), ('households_reached', 'Household members reached'), ('participants_supported', 'Participants who received support'), ('support_events', 'Support events delivered'), ('training_events', 'Training events delivered'), ('support_value', 'Value of support delivered'), ('harvest_quantity', 'Harvest quantity logged since start'), ('market_listings', 'Active market listings'), ('contracts_fulfilled', 'Contracts fulfilled since start')], max_length=30)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_defs', to='partners.programme')),
            ],
            options={
                'db_table': 'partner_indicators',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='indicatorreading',
            name='indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='partners.indicator'),
        ),
        migrations.CreateModel(
            name='ResultChain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('goal', 'Goal / Impact'), ('outcome', 'Outcome'), ('output', 'Output'), ('activity', 'Activity')], max_length=10)),
                ('code', models.CharField(blank=True, help_text='e.g. 1.2 or Output 3', max_length=20)),
                ('statement', models.CharField(max_length=500)),
                ('assumptions', models.TextField(blank=True, help_text='Assumptions / risks for this level')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='partners.resultchain')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_chain', to='partners.programme')),
            ],
            options={
                'db_table': 'partner_results_chain',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='indicator',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicators', to='partners.resultchain'),
        ),
        migrations.AlterUniqueTogether(
            name='indicator',
            unique_together={('programme', 'key')},
        ),
    ]
