# Generated by Django 5.1.4 on 2026-06-05 14:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('devices', '0001_initial'),
        ('enterprises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIVisionAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('analysis_type', models.CharField(choices=[('crop_disease', 'Crop Disease Detection'), ('pest_identification', 'Pest Identification'), ('livestock_health', 'Livestock Health Assessment'), ('livestock_count', 'Livestock Count'), ('field_survey', 'Field Survey / NDVI'), ('weed_detection', 'Weed Detection'), ('soil_assessment', 'Soil Assessment'), ('general', 'General Farm Analysis')], max_length=30)),
                ('image_url', models.TextField(blank=True)),
                ('user_description', models.TextField(blank=True)),
                ('diagnosis', models.CharField(blank=True, max_length=500)),
                ('severity', models.CharField(choices=[('none', 'None / Healthy'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='none', max_length=20)),
                ('confidence_pct', models.PositiveSmallIntegerField(default=0)),
                ('findings', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('ai_summary', models.TextField(blank=True)),
                ('extra_data', models.JSONField(default=dict)),
                ('is_public', models.BooleanField(default=False)),
                ('ai_model_used', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vision_analyses', to='enterprises.enterprisebatch')),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vision_analyses', to='enterprises.enterprise')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vision_analyses', to='accounts.organization')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vision_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vision_analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DroneFieldReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_health', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('critical', 'Critical')], default='good', max_length=20)),
                ('health_score', models.PositiveSmallIntegerField(default=75)),
                ('zones', models.JSONField(default=list)),
                ('detected_issues', models.JSONField(default=list)),
                ('action_plan', models.JSONField(default=list)),
                ('estimated_yield_impact_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drone_field_reports', to='enterprises.enterprise')),
                ('flight', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='field_report', to='devices.droneflight')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drone_field_reports', to='accounts.organization')),
                ('vision_analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drone_field_reports', to='vision.aivisionanalysis')),
            ],
            options={
                'db_table': 'drone_field_reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmerReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('crop_disease', 'Crop Disease'), ('pest', 'Pest / Insect'), ('animal_disease', 'Animal Disease'), ('nutritional', 'Nutritional Deficiency'), ('yield_issue', 'Yield Problem'), ('weed', 'Weed / Invasive'), ('soil', 'Soil Issue'), ('water', 'Water / Irrigation Issue'), ('equipment', 'Equipment Problem'), ('success', 'Success / Best Practice'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('crop_or_animal', models.CharField(blank=True, max_length=100)),
                ('location_hint', models.CharField(blank=True, max_length=255)),
                ('image_url', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('community', 'Community')], default='private', max_length=20)),
                ('helpful_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmer_reports', to='enterprises.enterprise')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_reports', to='accounts.organization')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmer_reports', to=settings.AUTH_USER_MODEL)),
                ('vision_analysis', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmer_report', to='vision.aivisionanalysis')),
            ],
            options={
                'db_table': 'farmer_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockCountLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('counted_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expected_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discrepancy', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discrepancy_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('status', models.CharField(choices=[('ok', 'OK — within tolerance'), ('discrepancy', 'Discrepancy — no sales order'), ('authorized', 'Authorized movement'), ('under_review', 'Under Review')], default='ok', max_length=20)),
                ('is_authorized', models.BooleanField(default=False)),
                ('authorization_ref', models.CharField(blank=True, max_length=255)),
                ('snapshot_url', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('counted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_count_logs', to='enterprises.enterprisebatch')),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_counts', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_count_logs', to='devices.device')),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_count_logs', to='enterprises.enterprise')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_count_logs', to='accounts.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_stock_counts', to=settings.AUTH_USER_MODEL)),
                ('vision_analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_count_logs', to='vision.aivisionanalysis')),
            ],
            options={
                'db_table': 'stock_count_logs',
                'ordering': ['-counted_at'],
            },
        ),
    ]
