# Generated by Django 4.2.13 on 2026-08-31 16:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vision', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerreport',
            name='helpful_users',
            field=models.ManyToManyField(blank=True, related_name='helpful_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
