# Generated by Django 5.1.4 on 2026-05-26 22:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('enterprises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_date', models.DateField()),
                ('record_type', models.CharField(choices=[('daily', 'Daily'), ('mortality', 'Mortality'), ('weight', 'Weight Check'), ('feed', 'Feed Record'), ('health', 'Health Check'), ('harvest', 'Harvest'), ('breeding', 'Breeding'), ('custom', 'Custom')], default='daily', max_length=30)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_records', to='enterprises.enterprisebatch')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_records', to='enterprises.enterprise')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_records', to='accounts.organization')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_records', to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_records', to='enterprises.enterprisestage')),
            ],
            options={
                'db_table': 'production_records',
                'ordering': ['-record_date', '-created_at'],
            },
        ),
    ]
