apiVersion: v1
kind: Service
metadata:
  name: agronexus-backend
  namespace: agronexus
spec:
  selector:
    app: agronexus-backend
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
