# Generated by Django 5.1.4 on 2026-09-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='data_sharing_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='data_sharing_consented_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='organization',
            name='org_type',
            field=models.CharField(choices=[('farm', 'Farm / Agribusiness'), ('government', 'Government Ministry / District Office'), ('ngo', 'NGO / Development Partner'), ('donor', 'Donor Programme')], default='farm', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('director', 'Director / Admin'), ('production_manager', 'Production Manager'), ('finance_manager', 'Finance Manager'), ('sales_manager', 'Sales Manager'), ('supervisor', 'Supervisor'), ('farmhand', 'Farmhand'), ('vet_officer', 'Veterinary Officer'), ('driver', 'Driver'), ('saas_admin', 'SaaS Platform Admin'), ('gov_viewer', 'Government / Partner Viewer')], default='farmhand', max_length=30),
        ),
    ]
