# Generated by Django 5.1.4 on 2026-09-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organization_data_sharing_consent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('director', 'Director / Admin'), ('production_manager', 'Production Manager'), ('finance_manager', 'Finance Manager'), ('sales_manager', 'Sales Manager'), ('supervisor', 'Supervisor'), ('farmhand', 'Farmhand'), ('vet_officer', 'Veterinary Officer'), ('driver', 'Driver'), ('saas_admin', 'SaaS Platform Admin'), ('gov_viewer', 'Government / Partner Viewer'), ('extension_officer', 'Extension Officer')], default='farmhand', max_length=30),
        ),
    ]
