# Generated by Django 5.1.4 on 2026-09-10 08:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_org_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('director', 'Director / Admin'), ('production_manager', 'Production Manager'), ('finance_manager', 'Finance Manager'), ('sales_manager', 'Sales Manager'), ('supervisor', 'Supervisor'), ('farmhand', 'Farmhand'), ('vet_officer', 'Veterinary Officer'), ('driver', 'Driver'), ('saas_admin', 'SaaS Platform Admin'), ('gov_viewer', 'Government / Partner Viewer'), ('extension_officer', 'Extension Officer'), ('partner_manager', 'Supporting Partner Programme Manager'), ('gov_admin', 'Government Administrator'), ('extension_supervisor', 'Extension Supervisor'), ('partner_admin', 'Supporting Partner Administrator'), ('partner_me_officer', 'Supporting Partner M&E Officer'), ('partner_observer', 'Supporting Partner Observer')], default='farmhand', max_length=30),
        ),
        migrations.CreateModel(
            name='AccessAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=40)),
                ('detail', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField()),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_audit', to='accounts.organization')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'access_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=30)),
                ('kind', models.CharField(default='site', max_length=20)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('is_headquarters', models.BooleanField(default=False, help_text='HQ members are organisation-wide, not branch-scoped')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='accounts.organization')),
            ],
            options={
                'db_table': 'org_branches',
                'ordering': ['-is_headquarters', 'name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounts.branch'),
        ),
    ]
