# Generated by Django 5.1.4 on 2026-09-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_is_org_admin_alter_profile_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='business_type',
            field=models.CharField(choices=[('farmer', 'Farm'), ('cooperative', 'Cooperative / Farmer Group'), ('agro_dealer', 'Agro Dealer / Input Shop'), ('vet_provider', 'Veterinary Services'), ('equipment_hire', 'Equipment Hire'), ('agrifood_seller', 'AgriFood Seller'), ('agrisupply_provider', 'AgriSupply Provider'), ('agriservices_provider', 'AgriServices Provider'), ('processor', 'Agro Processor'), ('transport', 'Transport & Logistics')], default='farmer', max_length=30),
        ),
    ]
