# Generated by Django 5.1.4 on 2026-09-11 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_organization_business_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantProfile',
            fields=[
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='participant_profile', serialize=False, to='accounts.organization')),
                ('head_sex', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('X', 'Other / prefer not to say')], max_length=1)),
                ('head_birth_year', models.PositiveIntegerField(blank=True, null=True)),
                ('household_size', models.PositiveIntegerField(blank=True, null=True)),
                ('female_members', models.PositiveIntegerField(blank=True, null=True)),
                ('male_members', models.PositiveIntegerField(blank=True, null=True)),
                ('youth_led', models.BooleanField(blank=True, help_text='Led by someone 35 or younger', null=True)),
                ('disability', models.BooleanField(default=False, help_text='Household includes a person with a disability')),
                ('land_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('national_id_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_participant_profile',
            },
        ),
    ]
