# Generated by Django 5.1.4 on 2026-10-06 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_participantprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgWorkspace',
            fields=[
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='workspace', serialize=False, to='accounts.organization')),
                ('org_data', models.JSONField(blank=True, default=dict)),
                ('cycles', models.JSONField(blank=True, default=list)),
                ('edit_requests', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_org_workspace',
            },
        ),
    ]
