# Generated by Django 5.1.4 on 2026-09-09 17:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_organization_data_sharing_consent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('weather', 'Weather Warning'), ('disease', 'Disease / Pest Alert'), ('market', 'Market / Price Notice'), ('programme', 'Programme / Subsidy'), ('general', 'General Advisory')], default='general', max_length=20)),
                ('priority', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=10)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('enterprise_category', models.CharField(blank=True, help_text='e.g. crop, livestock — blank = all', max_length=30)),
                ('farms_reached', models.PositiveIntegerField(default=0)),
                ('recipients_reached', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Issuing government / partner organisation', on_delete=django.db.models.deletion.CASCADE, related_name='advisories', to='accounts.organization')),
            ],
            options={
                'db_table': 'gov_advisories',
                'ordering': ['-created_at'],
            },
        ),
    ]
