# Generated by Django 5.1.4 on 2026-09-09 20:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_profile_role'),
        ('vision', '0002_farmerreport_helpful_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtensionVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visit_date', models.DateField()),
                ('visit_type', models.CharField(choices=[('field_visit', 'Field Visit'), ('phone', 'Phone Consultation'), ('video', 'Video Consultation'), ('training', 'Training / Field Day'), ('follow_up', 'Follow-up')], default='field_visit', max_length=20)),
                ('purpose', models.CharField(max_length=255)),
                ('findings', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('follow_up_done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension_visits', to='accounts.organization')),
                ('farmer_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extension_visits', to='vision.farmerreport')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'extension_visits',
                'ordering': ['-visit_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtensionCaseload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension_assignments', to='accounts.organization')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caseload', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'extension_caseloads',
                'ordering': ['-assigned_at'],
                'unique_together': {('officer', 'farm')},
            },
        ),
    ]
