# Generated by Django 5.1.4 on 2026-06-05 15:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('devices', '0001_initial'),
        ('enterprises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('equipment_type', models.CharField(choices=[('tractor', 'Tractor'), ('planter', 'Planter'), ('harvester', 'Harvester'), ('sprayer', 'Sprayer'), ('truck', 'Truck'), ('generator', 'Generator'), ('pump', 'Pump'), ('drone', 'Agricultural Drone'), ('implement', 'Implement'), ('other', 'Other')], default='tractor', max_length=20)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('year_manufactured', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('operational', 'Operational'), ('in_use', 'In Use'), ('maintenance', 'Under Maintenance'), ('repair', 'Needs Repair'), ('retired', 'Retired')], default='operational', max_length=20)),
                ('autonomous_level', models.CharField(choices=[('manual', 'Manual'), ('assisted', 'Driver Assisted'), ('semi_auto', 'Semi-Autonomous'), ('full_auto', 'Fully Autonomous')], default='manual', max_length=20)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gps_tracker_id', models.CharField(blank=True, max_length=100)),
                ('engine_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('odometer_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fuel_capacity_l', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('current_fuel_pct', models.PositiveSmallIntegerField(default=100)),
                ('service_interval_hours', models.PositiveIntegerField(default=250)),
                ('last_service_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('next_service_due', models.DateField(blank=True, null=True)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('device', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='devices.device')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='accounts.organization')),
            ],
            options={
                'db_table': 'equipment',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentTelemetry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('speed_kmh', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('heading_degrees', models.PositiveSmallIntegerField(default=0)),
                ('engine_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fuel_pct', models.PositiveSmallIntegerField(default=100)),
                ('rpm', models.PositiveIntegerField(default=0)),
                ('engine_temp_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_engine_on', models.BooleanField(default=False)),
                ('is_autonomous', models.BooleanField(default=False)),
                ('alerts', models.JSONField(default=list)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='equipment.equipment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            options={
                'db_table': 'equipment_telemetry',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='FieldOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_type', models.CharField(choices=[('ploughing', 'Ploughing'), ('discing', 'Discing'), ('planting', 'Planting'), ('spraying', 'Spraying'), ('fertilizing', 'Fertilizing'), ('harvesting', 'Harvesting'), ('mowing', 'Mowing'), ('baling', 'Baling'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('field_name', models.CharField(blank=True, max_length=255)),
                ('area_ha', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('scheduled_date', models.DateField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('fuel_used_l', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('hours_spent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gps_track', models.JSONField(default=list, help_text='List of [lat,lng] waypoints')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_operations', to='enterprises.enterprise')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='equipment.equipment')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_operations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_operations', to='accounts.organization')),
            ],
            options={
                'db_table': 'field_operations',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('maintenance_type', models.CharField(choices=[('service', 'Scheduled Service'), ('repair', 'Repair'), ('inspection', 'Inspection'), ('tyre', 'Tyre Change'), ('oil', 'Oil Change'), ('filter', 'Filter Replacement'), ('other', 'Other')], default='service', max_length=20)),
                ('description', models.TextField()),
                ('technician', models.CharField(blank=True, max_length=255)),
                ('parts_used', models.JSONField(default=list)),
                ('labour_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('parts_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('engine_hours_at_service', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('service_date', models.DateField()),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='equipment.equipment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            options={
                'db_table': 'maintenance_records',
                'ordering': ['-service_date'],
            },
        ),
    ]
