# Generated by Django 5.1.4 on 2026-06-05 19:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutonomousTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_type', models.CharField(max_length=100)),
                ('field_name', models.CharField(blank=True, max_length=255)),
                ('field_boundary', models.JSONField(default=list, help_text='GPS polygon for the field')),
                ('path_plan', models.JSONField(default=list, help_text='Generated waypoints')),
                ('speed_kmh', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('overlap_pct', models.PositiveSmallIntegerField(default=10)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent to Equipment'), ('executing', 'Executing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('progress_pct', models.PositiveSmallIntegerField(default=0)),
                ('area_completed_ha', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('scheduled_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autonomous_tasks', to='equipment.equipment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autonomous_tasks', to='accounts.organization')),
            ],
            options={
                'db_table': 'autonomous_tasks',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='ImplementAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('attachment_type', models.CharField(choices=[('plough', 'Plough'), ('disc_harrow', 'Disc Harrow'), ('ripper', 'Ripper'), ('planter', 'Planter'), ('sprayer_boom', 'Spray Boom'), ('spreader', 'Fertilizer Spreader'), ('mower', 'Mower/Slasher'), ('baler', 'Baler'), ('trailer', 'Trailer'), ('ridger', 'Ridger'), ('cultivator', 'Cultivator'), ('other', 'Other')], default='other', max_length=20)),
                ('width_m', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('condition', models.CharField(blank=True, help_text='Good, Fair, Poor', max_length=50)),
                ('is_available', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compatible_equipment', models.ManyToManyField(blank=True, related_name='compatible_implements', to='equipment.equipment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='implement_attachments', to='accounts.organization')),
            ],
            options={
                'db_table': 'implement_attachments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImplementUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(blank=True, max_length=255)),
                ('area_ha', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hours_used', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='implement_usage_logs', to='equipment.equipment')),
                ('field_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='implement_usage_logs', to='equipment.fieldoperation')),
                ('implement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='equipment.implementattachment')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            options={
                'db_table': 'implement_usage_logs',
                'ordering': ['-started_at'],
            },
        ),
    ]
