# Generated by Django 5.1.4 on 2026-08-31 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_autonomoustask_implementattachment_implementusagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='last_telemetry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
