# Generated by Django 5.1.4 on 2026-05-26 22:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('enterprises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('dropdown', 'Dropdown'), ('boolean', 'Yes/No'), ('image', 'Image'), ('gps', 'GPS Location'), ('sensor', 'Sensor'), ('formula', 'Formula')], max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('options', models.JSONField(default=list)),
                ('formula', models.TextField(blank=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('min_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('default_value', models.TextField(blank=True)),
                ('sensor_id', models.CharField(blank=True, max_length=100)),
                ('field_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='enterprises.enterprise')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='accounts.organization')),
            ],
            options={
                'db_table': 'custom_fields',
                'ordering': ['field_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('per_batch', 'Per Batch'), ('weekly', 'Weekly'), ('per_harvest', 'Per Harvest'), ('ad_hoc', 'Ad Hoc'), ('per_inspection', 'Per Inspection')], default='daily', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='enterprises.enterprise')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='accounts.organization')),
            ],
            options={
                'db_table': 'forms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('options', models.JSONField(default=list)),
                ('formula', models.TextField(blank=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('field_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('custom_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_usages', to='forms_engine.customfield')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='forms_engine.form')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            options={
                'db_table': 'form_fields',
                'ordering': ['field_order'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(default=dict)),
                ('gps_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('gps_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='enterprises.enterprisebatch')),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='enterprises.enterprise')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='forms_engine.form')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='accounts.organization')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'form_submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
