# Generated by Django 5.1.4 on 2026-05-26 22:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('enterprises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('device_type', models.CharField(choices=[('sensor', 'Sensor'), ('camera', 'Camera'), ('drone', 'Drone'), ('gateway', 'Gateway'), ('controller', 'Controller'), ('weighscale', 'Weigh Scale')], max_length=20)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('firmware_version', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('warning', 'Warning'), ('pairing', 'Pairing')], default='offline', max_length=20)),
                ('battery_pct', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('signal_strength', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='enterprises.enterprise')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='accounts.organization')),
                ('paired_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paired_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'devices',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CameraEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('motion', 'Motion'), ('intruder', 'Intruder'), ('livestock_count', 'Livestock Count'), ('disease_flag', 'Disease Flag'), ('face', 'Face Detected')], max_length=30)),
                ('confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('snapshot_url', models.URLField(blank=True)),
                ('video_clip_url', models.URLField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_events', to='accounts.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_events', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_events', to='devices.device')),
            ],
            options={
                'db_table': 'camera_events',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='DroneFlight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flight_type', models.CharField(choices=[('survey', 'Survey'), ('spray', 'Spray'), ('inspection', 'Inspection'), ('count', 'Livestock Count')], default='survey', max_length=20)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_flight', 'In Flight'), ('completed', 'Completed'), ('aborted', 'Aborted')], default='planned', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('flight_path', models.JSONField(blank=True, null=True)),
                ('area_covered_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('altitude_m', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('findings', models.JSONField(default=dict)),
                ('image_urls', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flights', to='devices.device')),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drone_flights', to='enterprises.enterprise')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drone_flights', to='accounts.organization')),
                ('piloted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drone_flights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'drone_flights',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('camera', 'Camera'), ('sensor', 'Sensor'), ('automation', 'Automation'), ('manual', 'Manual')], max_length=20)),
                ('source_id', models.UUIDField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_alerts', to='accounts.organization')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'security_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric', models.CharField(choices=[('dissolved_oxygen', 'Dissolved Oxygen'), ('ph', 'pH'), ('temperature', 'Temperature'), ('humidity', 'Humidity'), ('ammonia', 'Ammonia'), ('co2', 'CO2'), ('weight', 'Weight'), ('light', 'Light'), ('pressure', 'Pressure'), ('custom', 'Custom')], max_length=50)),
                ('value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unit', models.CharField(max_length=30)),
                ('is_alert', models.BooleanField(default=False)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='devices.device')),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensor_readings', to='enterprises.enterprise')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_readings', to='accounts.organization')),
            ],
            options={
                'db_table': 'sensor_readings',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
