# Generated by Django 5.1.4 on 2026-06-05 15:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('enterprises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('buyer_type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company'), ('exporter', 'Exporter'), ('processor', 'Processor'), ('restaurant', 'Restaurant / Hospitality'), ('supermarket', 'Supermarket'), ('ngo', 'NGO / Aid Organization'), ('government', 'Government')], default='company', max_length=20)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('town', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Zambia', max_length=100)),
                ('commodities_wanted', models.JSONField(default=list, help_text='List of commodity names they buy')),
                ('preferred_volume_kg', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('payment_terms', models.CharField(blank=True, help_text='COD, 30 days, etc.', max_length=255)),
                ('rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_profiles', to='accounts.organization')),
            ],
            options={
                'db_table': 'buyer_profiles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CommodityPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commodity', models.CharField(max_length=255)),
                ('market_name', models.CharField(max_length=255)),
                ('unit', models.CharField(choices=[('kg', 'per kg'), ('tonne', 'per tonne'), ('head', 'per head'), ('litre', 'per litre'), ('bag_50kg', 'per 50 kg bag'), ('crate', 'per crate'), ('each', 'each')], default='kg', max_length=20)),
                ('price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('currency', models.CharField(default='ZMW', max_length=10)),
                ('price_date', models.DateField()),
                ('source', models.CharField(blank=True, help_text='FRA, local market, buyer, etc.', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            options={
                'db_table': 'commodity_prices',
                'ordering': ['-price_date', 'commodity'],
            },
        ),
        migrations.CreateModel(
            name='MarketListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commodity', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('quantity_available', models.DecimalField(decimal_places=2, max_digits=14)),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('asking_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('currency', models.CharField(default='ZMW', max_length=10)),
                ('min_order_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Listed / Active'), ('negotiating', 'In Negotiation'), ('sold', 'Sold'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('available_until', models.DateField(blank=True, null=True)),
                ('delivery_available', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('photos', models.JSONField(default=list)),
                ('certifications', models.JSONField(default=list)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='enterprises.enterprise')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_listings', to='accounts.organization')),
            ],
            options={
                'db_table': 'market_listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuctionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('open', 'Open for Bids'), ('closed', 'Bidding Closed'), ('sold', 'Sold'), ('unsold', 'Passed In')], default='upcoming', max_length=20)),
                ('reserve_price', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('current_highest_bid', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('winning_bid', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('opens_at', models.DateTimeField()),
                ('closes_at', models.DateTimeField()),
                ('bids', models.JSONField(default=list, help_text='List of {buyer, amount, timestamp} dicts')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_events', to='accounts.organization')),
                ('winner_buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='market.buyerprofile')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='market.marketlisting')),
            ],
            options={
                'db_table': 'auction_events',
                'ordering': ['-opens_at'],
            },
        ),
        migrations.CreateModel(
            name='TradeContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commodity', models.CharField(max_length=255)),
                ('quantity_agreed', models.DecimalField(decimal_places=2, max_digits=14)),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('agreed_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('currency', models.CharField(default='ZMW', max_length=10)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('offered', 'Offer Sent'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('fulfilled', 'Fulfilled'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('delivery_address', models.TextField(blank=True)),
                ('payment_terms', models.TextField(blank=True)),
                ('deposit_pct', models.PositiveSmallIntegerField(default=0)),
                ('deposit_paid', models.BooleanField(default=False)),
                ('final_paid', models.BooleanField(default=False)),
                ('quantity_delivered', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='market.buyerprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='market.marketlisting')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_contracts', to='accounts.organization')),
            ],
            options={
                'db_table': 'trade_contracts',
                'ordering': ['-created_at'],
            },
        ),
    ]
