# Generated by Django 5.1.4 on 2026-06-05 19:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('market', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColdChainLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location_name', models.CharField(help_text='Truck, store, depot name', max_length=255)),
                ('commodity', models.CharField(max_length=255)),
                ('temp_min_target', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('temp_max_target', models.DecimalField(decimal_places=2, default=4, max_digits=5)),
                ('temperature_c', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity_pct', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ok', 'Within Range'), ('breach', 'Temperature Breach'), ('warning', 'Near Limit')], default='ok', max_length=10)),
                ('device_id', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('recorded_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cold_chain_logs', to='market.tradecontract')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cold_chain_logs', to='accounts.organization')),
            ],
            options={
                'db_table': 'cold_chain_logs',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='ExportDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('phytosanitary', 'Phytosanitary Certificate'), ('packing_list', 'Packing List'), ('invoice', 'Commercial Invoice'), ('coo', 'Certificate of Origin'), ('health_cert', 'Veterinary Health Certificate'), ('fumigation', 'Fumigation Certificate'), ('customs', 'Customs Declaration'), ('other', 'Other')], max_length=20)),
                ('doc_number', models.CharField(blank=True, max_length=100)),
                ('issuing_authority', models.CharField(blank=True, max_length=255)),
                ('commodity', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('destination_country', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for Approval'), ('approved', 'Approved / Issued'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('document_url', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_documents', to='market.tradecontract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_documents', to='accounts.organization')),
            ],
            options={
                'db_table': 'export_documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
