# Generated manually — AgroNexus Phase 3 marketplace providers
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_coldchainlog_exportdocument'),
        ('accounts', '0001_initial'),
        ('enterprises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ── Provider ──────────────────────────────────────────────────────────
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('provider_type', models.CharField(choices=[
                    ('agro_dealer','Agro Dealer / Input Supplier'),
                    ('equipment_hire','Equipment Hire'),
                    ('vet_services','Veterinary Services'),
                    ('processing','Agro Processing'),
                    ('transport','Transport & Logistics'),
                    ('finance','Agricultural Finance'),
                    ('insurance','Crop / Livestock Insurance'),
                    ('extension','Extension & Advisory Services'),
                    ('cold_storage','Cold Storage'),
                    ('certification','Certification & Inspection'),
                ], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('whatsapp', models.CharField(blank=True, max_length=50)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('town', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('coverage_districts', models.JSONField(default=list)),
                ('logo_url', models.CharField(blank=True, max_length=500)),
                ('cover_url', models.CharField(blank=True, max_length=500)),
                ('photos', models.JSONField(default=list)),
                ('status', models.CharField(choices=[
                    ('pending','Pending Review'),('active','Active / Verified'),
                    ('suspended','Suspended'),('inactive','Inactive'),
                ], default='pending', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('trust_score', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('year_established', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('business_reg_no', models.CharField(blank=True, max_length=100)),
                ('tax_id', models.CharField(blank=True, max_length=100)),
                ('tags', models.JSONField(default=list)),
                ('specialties', models.JSONField(default=list)),
                ('service_hours', models.CharField(blank=True, max_length=255)),
                ('mobile_service', models.BooleanField(default=False)),
                ('emergency_available', models.BooleanField(default=False)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('booking_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_providers', to='accounts.organization')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_providers', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_providers', to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'market_providers', 'ordering': ['-avg_rating', 'name']},
        ),

        # ── ProviderStaff ─────────────────────────────────────────────────────
        migrations.CreateModel(
            name='ProviderStaff',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[
                    ('owner','Owner / Director'),('manager','Branch Manager'),('vet_officer','Veterinary Officer'),
                    ('agronomist','Agronomist'),('sales_rep','Sales Representative'),('technician','Technician'),
                    ('driver','Driver / Delivery'),('other','Other'),
                ], default='other', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('qualifications', models.JSONField(default=list)),
                ('photo_url', models.CharField(blank=True, max_length=500)),
                ('licence_no', models.CharField(blank=True, max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='market.provider')),
            ],
            options={'db_table': 'provider_staff', 'ordering': ['name']},
        ),

        # ── ProviderService ───────────────────────────────────────────────────
        migrations.CreateModel(
            name='ProviderService',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('pricing_model', models.CharField(choices=[
                    ('fixed','Fixed Price'),('per_unit','Per Unit'),('per_ha','Per Hectare'),
                    ('per_head','Per Head'),('per_hour','Per Hour'),('per_day','Per Day'),
                    ('per_km','Per km'),('negotiable','Negotiable / Quote'),('free','Free'),
                ], default='negotiable', max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='ZMW', max_length=10)),
                ('unit_label', models.CharField(blank=True, max_length=50)),
                ('is_available', models.BooleanField(default=True)),
                ('lead_time_days', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='market.provider')),
            ],
            options={'db_table': 'provider_services', 'ordering': ['name']},
        ),

        # ── ProviderCertification ─────────────────────────────────────────────
        migrations.CreateModel(
            name='ProviderCertification',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('issuing_body', models.CharField(blank=True, max_length=255)),
                ('cert_number', models.CharField(blank=True, max_length=100)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('valid','Valid'),('expired','Expired'),('pending','Pending Renewal')], default='valid', max_length=10)),
                ('document_url', models.CharField(blank=True, max_length=500)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='market.provider')),
            ],
            options={'db_table': 'provider_certifications', 'ordering': ['name']},
        ),

        # ── ProviderReview ────────────────────────────────────────────────────
        migrations.CreateModel(
            name='ProviderReview',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('rating', models.PositiveSmallIntegerField()),
                ('title', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('service_used', models.CharField(blank=True, max_length=255)),
                ('verified_purchase', models.BooleanField(default=False)),
                ('helpful_votes', models.PositiveIntegerField(default=0)),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='market.provider')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_reviews', to='accounts.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'provider_reviews', 'ordering': ['-created_at'], 'unique_together': {('provider', 'organization')}},
        ),

        # ── EquipmentCatalog ──────────────────────────────────────────────────
        migrations.CreateModel(
            name='EquipmentCatalog',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('equipment_type', models.CharField(choices=[
                    ('tractor','Tractor'),('plough','Plough / Ridger'),('planter','Planter'),
                    ('harvester','Combine Harvester'),('sprayer','Sprayer'),('drone','Agricultural Drone'),
                    ('irrigation','Irrigation System / Centre Pivot'),('truck','Truck / Transport'),
                    ('generator','Generator'),('storage','Storage Equipment'),
                    ('processing','Processing Equipment'),('other','Other'),
                ], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('make', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('capacity', models.CharField(blank=True, max_length=100)),
                ('daily_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('per_ha_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='ZMW', max_length=10)),
                ('operator_included', models.BooleanField(default=True)),
                ('fuel_included', models.BooleanField(default=False)),
                ('min_hire_days', models.PositiveSmallIntegerField(default=1)),
                ('photos', models.JSONField(default=list)),
                ('specs', models.JSONField(default=dict)),
                ('is_available', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='market.provider')),
            ],
            options={'db_table': 'provider_equipment_catalog', 'ordering': ['equipment_type', 'name']},
        ),

        # ── HireBooking ───────────────────────────────────────────────────────
        migrations.CreateModel(
            name='HireBooking',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('booking_ref', models.CharField(blank=True, max_length=30, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('hectares', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[
                    ('enquiry','Enquiry'),('quoted','Quote Sent'),('confirmed','Confirmed'),
                    ('active','In Use / On-site'),('completed','Completed'),('cancelled','Cancelled'),
                ], default='enquiry', max_length=20)),
                ('quoted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('agreed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='ZMW', max_length=10)),
                ('deposit_paid', models.BooleanField(default=False)),
                ('final_paid', models.BooleanField(default=False)),
                ('delivery_address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('provider_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hire_bookings', to='market.provider')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='market.equipmentcatalog')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hire_bookings', to='accounts.organization')),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hire_bookings', to='enterprises.enterprise')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hire_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={'db_table': 'provider_hire_bookings', 'ordering': ['-created_at']},
        ),

        # ── VetAppointment ────────────────────────────────────────────────────
        migrations.CreateModel(
            name='VetAppointment',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('appt_ref', models.CharField(blank=True, max_length=30, unique=True)),
                ('appt_type', models.CharField(choices=[
                    ('consultation','General Consultation'),('vaccination','Vaccination'),
                    ('treatment','Treatment / Procedure'),('diagnosis','Diagnosis / Lab'),
                    ('deworming','Deworming'),('pregnancy','Pregnancy Check'),
                    ('slaughter_cert','Pre-slaughter Certification'),
                    ('teleconsult','Teleconsultation (Remote)'),('other','Other'),
                ], max_length=20)),
                ('appt_date', models.DateField()),
                ('appt_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[
                    ('requested','Requested'),('confirmed','Confirmed'),
                    ('in_progress','In Progress'),('completed','Completed'),
                    ('no_show','No Show'),('cancelled','Cancelled'),
                ], default='requested', max_length=20)),
                ('species', models.CharField(blank=True, max_length=100)),
                ('animal_count', models.PositiveIntegerField(default=0)),
                ('symptoms', models.TextField(blank=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('treatment_given', models.TextField(blank=True)),
                ('medications', models.JSONField(default=list)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('outcome_notes', models.TextField(blank=True)),
                ('consultation_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='ZMW', max_length=10)),
                ('paid', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vet_appointments', to='market.provider')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vet_appointments', to='accounts.organization')),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vet_appointments', to='enterprises.enterprise')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vet_appointments', to=settings.AUTH_USER_MODEL)),
                ('vet_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='market.providerstaff')),
            ],
            options={'db_table': 'provider_vet_appointments', 'ordering': ['-appt_date', '-created_at']},
        ),
    ]
