# Generated by Django 5.1.4 on 2026-08-31 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_provider_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vetappointment',
            name='notes',
        ),
        migrations.AlterField(
            model_name='equipmentcatalog',
            name='capacity',
            field=models.CharField(blank=True, help_text='e.g. 90HP, 3.5t, 36m wingspan', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipmentcatalog',
            name='specs',
            field=models.JSONField(default=dict, help_text='Additional specs as key-value pairs'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='coverage_districts',
            field=models.JSONField(default=list, help_text='Districts this provider serves'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='mobile_service',
            field=models.BooleanField(default=False, help_text='Provider comes to the farm'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='service_hours',
            field=models.CharField(blank=True, help_text='e.g. Mon-Fri 08:00-17:00', max_length=255),
        ),
        migrations.AlterField(
            model_name='provider',
            name='specialties',
            field=models.JSONField(default=list, help_text='Crops, species, or domains of expertise'),
        ),
        migrations.AlterField(
            model_name='providercertification',
            name='issuing_body',
            field=models.CharField(blank=True, help_text='e.g. SCCI, ZABS, ZEMA, HPCZ', max_length=255),
        ),
        migrations.AlterField(
            model_name='providercertification',
            name='name',
            field=models.CharField(help_text='e.g. SCCI Registered Dealer', max_length=255),
        ),
        migrations.AlterField(
            model_name='providercertification',
            name='verified',
            field=models.BooleanField(default=False, help_text='Platform admin has verified this cert'),
        ),
        migrations.AlterField(
            model_name='providerreview',
            name='rating',
            field=models.PositiveSmallIntegerField(help_text='1–5'),
        ),
        migrations.AlterField(
            model_name='providerreview',
            name='verified_purchase',
            field=models.BooleanField(default=False, help_text='Linked to a confirmed booking'),
        ),
        migrations.AlterField(
            model_name='providerservice',
            name='lead_time_days',
            field=models.PositiveSmallIntegerField(default=0, help_text='Typical lead time'),
        ),
        migrations.AlterField(
            model_name='providerservice',
            name='price_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Upper bound for price ranges', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='providerservice',
            name='unit_label',
            field=models.CharField(blank=True, help_text='e.g. "50kg bag", "per animal"', max_length=50),
        ),
        migrations.AlterField(
            model_name='providerstaff',
            name='licence_no',
            field=models.CharField(blank=True, help_text='HPCZ/VRAZ/ZEMA licence number', max_length=100),
        ),
        migrations.AlterField(
            model_name='vetappointment',
            name='medications',
            field=models.JSONField(default=list, help_text='[{name, dose, route, days}]'),
        ),
        migrations.AlterField(
            model_name='vetappointment',
            name='species',
            field=models.CharField(blank=True, help_text='e.g. Broilers, Tilapia, Cattle', max_length=100),
        ),
    ]
