# Generated by Django 5.1.4 on 2026-05-26 22:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('enterprises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('aggregation', models.CharField(choices=[('average', 'Average'), ('sum', 'Sum'), ('latest', 'Latest'), ('min', 'Minimum'), ('max', 'Maximum')], default='average', max_length=20)),
                ('target', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('warning_threshold', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('critical_threshold', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('higher_is_better', models.BooleanField(default=True)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('category', models.CharField(choices=[('production', 'Production'), ('financial', 'Financial'), ('health', 'Health'), ('quality', 'Quality'), ('efficiency', 'Efficiency'), ('environmental', 'Environmental')], default='production', max_length=30)),
                ('formula', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='enterprises.enterprise')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='accounts.organization')),
            ],
            options={
                'db_table': 'kpi_definitions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KPIValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=4, max_digits=14)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('formula', 'Formula'), ('sensor', 'Sensor'), ('import', 'Import')], default='manual', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_values', to='enterprises.enterprisebatch')),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_values', to='enterprises.enterprise')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='kpis.kpidefinition')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kpi_values',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
