apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: agronexus-backend-hpa
  namespace: agronexus
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: agronexus-backend
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: agronexus-celery-hpa
  namespace: agronexus
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: agronexus-celery-worker
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
