# Generated by Django 5.1.4 on 2026-06-05 15:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('devices', '0001_initial'),
        ('enterprises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('area_ha', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('crop_type', models.CharField(blank=True, max_length=100)),
                ('crop_stage', models.CharField(choices=[('fallow', 'Fallow'), ('land_prep', 'Land Preparation'), ('planting', 'Planted'), ('vegetative', 'Vegetative Growth'), ('flowering', 'Flowering / Pollination'), ('fruiting', 'Fruiting'), ('harvest_ready', 'Ready to Harvest'), ('harvested', 'Harvested')], default='fallow', max_length=20)),
                ('planting_date', models.DateField(blank=True, null=True)),
                ('expected_harvest_date', models.DateField(blank=True, null=True)),
                ('soil_type', models.CharField(blank=True, max_length=100)),
                ('gps_boundary', models.JSONField(default=list, help_text='Polygon as list of [lat,lng] points')),
                ('latest_ndvi', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('latest_ndvi_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farm_fields', to='enterprises.enterprise')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_fields', to='accounts.organization')),
            ],
            options={
                'db_table': 'farm_fields',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NDVIRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ndvi_value', models.DecimalField(decimal_places=4, help_text='-1.0 to 1.0', max_digits=5)),
                ('source', models.CharField(choices=[('drone', 'Drone'), ('satellite', 'Satellite'), ('manual', 'Manual Estimate')], default='satellite', max_length=20)),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('health_assessment', models.CharField(blank=True, max_length=255)),
                ('zones', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('recorded_at', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ndvi_records', to='weather.farmfield')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            options={
                'db_table': 'ndvi_records',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('station_id', models.CharField(blank=True, help_text='External provider ID', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('altitude_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.CharField(blank=True, help_text='e.g. OpenWeather, Davis, in-house', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weather_station', to='devices.device')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_stations', to='accounts.organization')),
            ],
            options={
                'db_table': 'weather_stations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WeatherReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('humidity_pct', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('wind_speed_kmh', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('wind_direction_deg', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rainfall_mm', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('pressure_hpa', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('uv_index', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('solar_radiation_wm2', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('dew_point_c', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_alert', models.BooleanField(default=False)),
                ('alert_type', models.CharField(blank=True, max_length=100)),
                ('recorded_at', models.DateTimeField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='weather.weatherstation')),
            ],
            options={
                'db_table': 'weather_readings',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddField(
            model_name='farmfield',
            name='nearest_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fields', to='weather.weatherstation'),
        ),
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('forecast_date', models.DateField()),
                ('condition', models.CharField(choices=[('sunny', 'Sunny'), ('partly_cloudy', 'Partly Cloudy'), ('cloudy', 'Cloudy'), ('light_rain', 'Light Rain'), ('heavy_rain', 'Heavy Rain'), ('thunderstorm', 'Thunderstorm'), ('frost', 'Frost Risk'), ('heat_wave', 'Heat Wave'), ('drought', 'Drought Warning')], default='sunny', max_length=20)),
                ('temp_min_c', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('temp_max_c', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rain_probability_pct', models.PositiveSmallIntegerField(default=0)),
                ('expected_rainfall_mm', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('wind_speed_kmh', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('farming_advisory', models.TextField(blank=True, help_text='AI-generated farming tip for this forecast')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='weather.weatherstation')),
            ],
            options={
                'db_table': 'weather_forecasts',
                'ordering': ['forecast_date'],
                'unique_together': {('station', 'forecast_date')},
            },
        ),
    ]
