# Generated by Django 5.1.4 on 2026-10-07 15:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_orgworkspace'),
        ('enterprises', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='legacy_id',
            field=models.CharField(blank=True, help_text='Id from the old browser-only record, for idempotent import', max_length=64),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='destination',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='movement_date',
            field=models.DateField(blank=True, help_text='The day the stock moved (recorded_at is when it was typed in)', null=True),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='source',
            field=models.CharField(default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='source_ref',
            field=models.CharField(blank=True, help_text='Idempotency key for automatic postings', max_length=120),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('feed', 'Feed'), ('medicine', 'Medicine'), ('seed', 'Seed'), ('fertiliser', 'Fertiliser'), ('equipment', 'Equipment'), ('chemical', 'Chemical'), ('packaging', 'Packaging'), ('produce', 'Produce'), ('processed', 'Processed goods'), ('other', 'Other')], default='feed', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(condition=models.Q(('legacy_id', ''), _negated=True), fields=('organization', 'legacy_id'), name='uniq_inv_item_legacy'),
        ),
        migrations.AddConstraint(
            model_name='inventorytransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('source_ref', ''), _negated=True), fields=('organization', 'source_ref'), name='uniq_inv_tx_source_ref'),
        ),
    ]
