# Generated by Django 5.1.4 on 2026-06-05 14:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('enterprises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_date', models.DateField()),
                ('title', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_plans', to='enterprises.enterprisebatch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_daily_plans', to=settings.AUTH_USER_MODEL)),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_plans', to='enterprises.enterprise')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_plans', to='accounts.organization')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_daily_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_plans',
                'ordering': ['-plan_date', '-created_at'],
                'unique_together': {('organization', 'enterprise', 'plan_date')},
            },
        ),
        migrations.CreateModel(
            name='DailyPlanTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('task_type', models.CharField(choices=[('feeding', 'Feeding'), ('health_check', 'Health Check'), ('harvest', 'Harvesting'), ('irrigation', 'Irrigation'), ('spraying', 'Spraying / Chemicals'), ('weeding', 'Weeding'), ('pruning', 'Pruning'), ('planting', 'Planting / Transplanting'), ('record_keeping', 'Record Keeping'), ('cleaning', 'Cleaning / Sanitation'), ('equipment', 'Equipment Maintenance'), ('transport', 'Transport / Delivery'), ('marketing', 'Marketing / Sales'), ('other', 'Other')], default='other', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('estimated_duration_hours', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('done', 'Done'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('completion_notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_tasks', to=settings.AUTH_USER_MODEL)),
                ('daily_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='plans.dailyplan')),
            ],
            options={
                'db_table': 'daily_plan_tasks',
                'ordering': ['sort_order', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_type', models.CharField(choices=[('enterprise_plan', 'Enterprise Plan'), ('daily_plan', 'Daily Plan'), ('marketing_plan', 'Marketing Plan'), ('budget_plan', 'Budget Plan'), ('seasonal_plan', 'Seasonal Plan')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('initiate_product', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_plans', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='enterprises.enterprisebatch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plans', to=settings.AUTH_USER_MODEL)),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='enterprises.enterprise')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='accounts.organization')),
            ],
            options={
                'db_table': 'plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketingPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_market', models.CharField(blank=True, max_length=255)),
                ('target_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('expected_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expected_unit', models.CharField(default='kg', max_length=50)),
                ('expected_unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('channels', models.JSONField(default=list)),
                ('key_activities', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_detail', to='plans.plan')),
            ],
            options={
                'db_table': 'marketing_plans',
            },
        ),
        migrations.CreateModel(
            name='PlanBudgetItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('labor', 'Labor'), ('materials', 'Materials'), ('equipment', 'Equipment / Tools'), ('seeds_livestock', 'Seeds / Livestock'), ('feeds', 'Feeds'), ('chemicals', 'Chemicals / Pesticides'), ('transport', 'Transport'), ('marketing', 'Marketing'), ('utilities', 'Utilities'), ('other', 'Other')], max_length=30)),
                ('item_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('unit', models.CharField(default='unit', max_length=50)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='plans.plan')),
            ],
            options={
                'db_table': 'plan_budget_items',
                'ordering': ['category', 'item_name'],
            },
        ),
    ]
