# Generated by Django 5.1.4 on 2026-06-05 15:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('devices', '0001_initial'),
        ('enterprises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IrrigationZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('zone_type', models.CharField(choices=[('drip', 'Drip Irrigation'), ('sprinkler', 'Sprinkler'), ('flood', 'Flood / Furrow'), ('centre_pivot', 'Centre Pivot'), ('manual', 'Manual')], default='drip', max_length=20)),
                ('water_source', models.CharField(choices=[('borehole', 'Borehole'), ('river', 'River'), ('dam', 'Dam'), ('municipal', 'Municipal'), ('rainwater', 'Rainwater Harvesting'), ('other', 'Other')], default='borehole', max_length=20)),
                ('area_ha', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('flow_rate_lph', models.DecimalField(decimal_places=2, default=0, help_text='Litres per hour', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_watering', models.BooleanField(default=False)),
                ('moisture_min_pct', models.PositiveSmallIntegerField(default=30)),
                ('moisture_max_pct', models.PositiveSmallIntegerField(default=70)),
                ('current_moisture_pct', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('crop_type', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('location_coords', models.CharField(blank=True, help_text='lat,lng', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='irrigation_zones', to='devices.device')),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='irrigation_zones', to='enterprises.enterprise')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_zones', to='accounts.organization')),
            ],
            options={
                'db_table': 'irrigation_zones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IrrigationSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('frequency', models.CharField(choices=[('daily', 'Every Day'), ('every_other', 'Every Other Day'), ('weekly', 'Weekly'), ('custom', 'Custom Days'), ('sensor', 'Sensor Triggered')], default='daily', max_length=20)),
                ('days_of_week', models.JSONField(default=list, help_text='e.g. ["Mon","Wed","Fri"]')),
                ('start_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('sensor_trigger', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='irrigation.irrigationzone')),
            ],
            options={
                'db_table': 'irrigation_schedules',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='IrrigationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger', models.CharField(choices=[('scheduled', 'Scheduled'), ('manual', 'Manual Override'), ('sensor', 'Sensor Triggered'), ('emergency', 'Emergency Stop')], default='scheduled', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('volume_litres', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('moisture_before', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('moisture_after', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cost_estimate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_events', to='accounts.organization')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='irrigation.irrigationschedule')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='irrigation.irrigationzone')),
            ],
            options={
                'db_table': 'irrigation_events',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SoilMoistureReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('moisture_pct', models.PositiveSmallIntegerField()),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_alert', models.BooleanField(default=False)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moisture_readings', to='irrigation.irrigationzone')),
            ],
            options={
                'db_table': 'soil_moisture_readings',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
