# Generated by Django 5.1.4 on 2026-06-05 19:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('devices', '0001_initial'),
        ('irrigation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoreholeMonitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('borehole_depth_m', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('tank_capacity_litres', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('current_level_pct', models.PositiveSmallIntegerField(default=100)),
                ('low_level_threshold_pct', models.PositiveSmallIntegerField(default=20)),
                ('pump_status', models.CharField(choices=[('running', 'Running'), ('idle', 'Idle'), ('fault', 'Fault'), ('off', 'Off')], default='idle', max_length=20)),
                ('pump_runtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('daily_output_litres', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('last_reading_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borehole_monitors', to='devices.device')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borehole_monitors', to='accounts.organization')),
            ],
            options={
                'db_table': 'borehole_monitors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TankLevelReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level_pct', models.PositiveSmallIntegerField()),
                ('volume_litres', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pump_running', models.BooleanField(default=False)),
                ('is_alert', models.BooleanField(default=False)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('borehole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_readings', to='irrigation.boreholemonitor')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            options={
                'db_table': 'tank_level_readings',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
