# Generated by Django 5.1.4 on 2026-06-05 15:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('enterprises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchFinancials',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_name', models.CharField(max_length=255)),
                ('batch_ref', models.CharField(blank=True, help_text='External batch/cycle reference', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('total_costs', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('break_even_units', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('break_even_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('target_units', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financials', to='enterprises.enterprise')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_financials', to='accounts.organization')),
            ],
            options={
                'db_table': 'batch_financials',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='BreakEvenAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('fixed_costs', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('variable_cost_per_unit', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('selling_price_per_unit', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('expected_units', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('contribution_margin', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('break_even_units', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('break_even_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('margin_of_safety_units', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('margin_of_safety_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('projected_profit', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch_financials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakeven_analyses', to='financials.batchfinancials')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakeven_analyses', to='accounts.organization')),
            ],
            options={
                'db_table': 'breakeven_analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CostEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('feed', 'Feed & Nutrition'), ('stock', 'Livestock / Seed Purchase'), ('vet', 'Veterinary & Health'), ('labour', 'Labour'), ('equipment', 'Equipment & Machinery'), ('fuel', 'Fuel & Energy'), ('water', 'Water'), ('packaging', 'Packaging'), ('transport', 'Transport & Logistics'), ('marketing', 'Marketing'), ('overhead', 'Overheads'), ('other', 'Other')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('quantity', models.DecimalField(decimal_places=4, default=1, max_digits=12)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('entry_date', models.DateField()),
                ('invoice_ref', models.CharField(blank=True, max_length=100)),
                ('supplier', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch_financials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_entries', to='financials.batchfinancials')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_entries', to='accounts.organization')),
            ],
            options={
                'db_table': 'cost_entries',
                'ordering': ['-entry_date'],
            },
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loan_type', models.CharField(choices=[('seasonal', 'Seasonal / Input Loan'), ('equipment', 'Equipment Finance'), ('land', 'Land Purchase'), ('infrastructure', 'Infrastructure'), ('working_capital', 'Working Capital'), ('emergency', 'Emergency')], default='seasonal', max_length=20)),
                ('lender_name', models.CharField(max_length=255)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=16)),
                ('amount_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('interest_rate_pct', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('term_months', models.PositiveSmallIntegerField(default=12)),
                ('monthly_repayment', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('disbursed', 'Disbursed'), ('rejected', 'Rejected'), ('repaying', 'Repaying'), ('settled', 'Settled')], default='draft', max_length=20)),
                ('purpose', models.TextField()),
                ('collateral', models.TextField(blank=True)),
                ('application_date', models.DateField(blank=True, null=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('disbursement_date', models.DateField(blank=True, null=True)),
                ('repayment_start', models.DateField(blank=True, null=True)),
                ('ai_credit_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ai_risk_assessment', models.TextField(blank=True)),
                ('ai_recommendation', models.CharField(blank=True, max_length=50)),
                ('documents', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to='accounts.organization')),
            ],
            options={
                'db_table': 'loan_applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RevenueEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('sales_live', 'Live Animal Sales'), ('sales_processed', 'Processed Product Sales'), ('sales_crop', 'Crop / Produce Sales'), ('milk', 'Milk Sales'), ('eggs', 'Egg Sales'), ('wool_hide', 'Wool / Hide'), ('subsidy', 'Government Subsidy / Grant'), ('insurance', 'Insurance Payout'), ('carbon_credit', 'Carbon Credits'), ('other', 'Other')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('quantity', models.DecimalField(decimal_places=4, default=1, max_digits=12)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('buyer', models.CharField(blank=True, max_length=255)),
                ('entry_date', models.DateField()),
                ('invoice_ref', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch_financials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_entries', to='financials.batchfinancials')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_entries', to='accounts.organization')),
            ],
            options={
                'db_table': 'revenue_entries',
                'ordering': ['-entry_date'],
            },
        ),
    ]
