# Generated by Django 5.1.4 on 2026-06-05 19:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('enterprises', '0001_initial'),
        ('financials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim_type', models.CharField(choices=[('crop_loss', 'Crop Loss / Drought'), ('flood', 'Flood Damage'), ('fire', 'Fire'), ('livestock_death', 'Livestock Death / Disease'), ('equipment', 'Equipment Damage'), ('theft', 'Theft'), ('other', 'Other')], max_length=20)),
                ('insurer_name', models.CharField(max_length=255)),
                ('policy_number', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('estimated_loss', models.DecimalField(decimal_places=2, max_digits=16)),
                ('amount_claimed', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('amount_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_assessment', 'Under Assessment'), ('approved', 'Approved'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('incident_date', models.DateField()),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('assessment_date', models.DateField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('evidence_urls', models.JSONField(default=list)),
                ('ndvi_evidence', models.TextField(blank=True, help_text='NDVI field health data as evidence')),
                ('weather_evidence', models.TextField(blank=True, help_text='Weather station data as evidence')),
                ('assessor_notes', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_claims', to='enterprises.enterprise')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_claims', to='accounts.organization')),
            ],
            options={
                'db_table': 'insurance_claims',
                'ordering': ['-incident_date'],
            },
        ),
    ]
