# Generated by Django 5.1.4 on 2026-09-10 04:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_role'),
        ('financials', '0002_insuranceclaim'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditShareGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lender_name', models.CharField(max_length=255)),
                ('lender_contact', models.CharField(blank=True, help_text='Email or phone of the credit officer', max_length=255)),
                ('purpose', models.CharField(blank=True, help_text='e.g. Seasonal input loan application', max_length=255)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('is_revoked', models.BooleanField(default=False)),
                ('access_count', models.PositiveIntegerField(default=0)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_share_grants', to='accounts.organization')),
            ],
            options={
                'db_table': 'credit_share_grants',
                'ordering': ['-created_at'],
            },
        ),
    ]
