# Generated by Django 5.1.4 on 2026-10-07 10:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_orgworkspace'),
        ('financials', '0003_creditsharegrant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tx_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('category', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date', models.DateField()),
                ('cycle_ref', models.CharField(blank=True, help_text='Production cycle id in the farm workspace', max_length=64)),
                ('reference', models.CharField(blank=True, help_text='Receipt / invoice number', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('source', models.CharField(default='manual', max_length=20)),
                ('source_ref', models.CharField(blank=True, help_text='Idempotency key for automatic postings', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_transactions', to='accounts.organization')),
            ],
            options={
                'db_table': 'farm_transactions',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['organization', 'date'], name='farm_transa_organiz_d5cbf9_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('source_ref', ''), _negated=True), fields=('organization', 'source_ref'), name='uniq_farm_tx_source_ref')],
            },
        ),
    ]
