# Generated by Django 5.1.4 on 2026-06-05 15:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('enterprises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('emission', 'Emission'), ('offset', 'Carbon Offset / Sequestration')], default='emission', max_length=10)),
                ('category', models.CharField(choices=[('fuel', 'Fuel Combustion'), ('electricity', 'Electricity Use'), ('enteric', 'Enteric Fermentation (Livestock)'), ('manure', 'Manure Management'), ('fertilizer', 'Synthetic Fertilizer'), ('transport', 'Transport & Logistics'), ('packaging', 'Packaging'), ('deforestation', 'Land Use Change'), ('other', 'Other')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=4, help_text='Source quantity, e.g. litres of diesel', max_digits=12)),
                ('unit', models.CharField(help_text='e.g. litres, kWh, head, tonnes', max_length=30)),
                ('co2e_kg', models.DecimalField(decimal_places=4, help_text='CO2 equivalent in kg', max_digits=14)),
                ('emission_factor', models.DecimalField(decimal_places=6, default=0, help_text='kg CO2e per unit', max_digits=10)),
                ('credit_value', models.DecimalField(decimal_places=2, default=0, help_text='Value of carbon credits if offset', max_digits=12)),
                ('entry_date', models.DateField()),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carbon_entries', to='enterprises.enterprise')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carbon_entries', to='accounts.organization')),
            ],
            options={
                'db_table': 'carbon_entries',
                'ordering': ['-entry_date'],
            },
        ),
        migrations.CreateModel(
            name='CertificationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certification_name', models.CharField(help_text='e.g. GlobalG.A.P., Organic, Rainforest Alliance', max_length=255)),
                ('certifying_body', models.CharField(max_length=255)),
                ('certificate_number', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('in_progress', 'In Progress'), ('certified', 'Certified'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='planning', max_length=20)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('scope', models.TextField(blank=True, help_text='What products/activities are covered')),
                ('document_url', models.CharField(blank=True, max_length=500)),
                ('renewal_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='accounts.organization')),
            ],
            options={
                'db_table': 'certification_records',
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='AuditRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auditor_name', models.CharField(max_length=255)),
                ('auditor_company', models.CharField(blank=True, max_length=255)),
                ('audit_date', models.DateField()),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('minor_nc', 'Minor Non-Conformance'), ('major_nc', 'Major Non-Conformance'), ('critical_nc', 'Critical Non-Conformance'), ('pending', 'Pending Review')], default='pending', max_length=20)),
                ('score_pct', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('findings', models.JSONField(default=list)),
                ('corrective_actions', models.JSONField(default=list)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('report_url', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_records', to='accounts.organization')),
                ('certification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to='sustainability.certificationrecord')),
            ],
            options={
                'db_table': 'audit_records',
                'ordering': ['-audit_date'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('done', 'Completed'), ('overdue', 'Overdue')], default='open', max_length=20)),
                ('due_date', models.DateField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('evidence_url', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_tasks', to=settings.AUTH_USER_MODEL)),
                ('certification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='sustainability.certificationrecord')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_tasks', to='accounts.organization')),
            ],
            options={
                'db_table': 'compliance_tasks',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='WaterUsageEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('borehole', 'Borehole'), ('river', 'River Abstraction'), ('dam', 'Dam / Reservoir'), ('rainwater', 'Rainwater Harvesting'), ('municipal', 'Municipal Supply'), ('recycled', 'Recycled / Treated')], max_length=20)),
                ('use_type', models.CharField(choices=[('irrigation', 'Crop Irrigation'), ('livestock', 'Livestock Watering'), ('cleaning', 'Facility Cleaning'), ('processing', 'Product Processing'), ('domestic', 'Domestic / Staff'), ('other', 'Other')], max_length=20)),
                ('volume_m3', models.DecimalField(decimal_places=3, max_digits=12)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('entry_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='water_entries', to='enterprises.enterprise')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_entries', to='accounts.organization')),
            ],
            options={
                'db_table': 'water_usage_entries',
                'ordering': ['-entry_date'],
            },
        ),
    ]
