# Generated by Django 5.1.4 on 2026-06-05 19:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('enterprises', '0001_initial'),
        ('sustainability', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManureBiogasRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_type', models.CharField(choices=[('manure_collected', 'Manure Collected'), ('biogas_output', 'Biogas Output'), ('compost_turned', 'Compost Turned'), ('compost_ready', 'Compost Ready'), ('effluent_treated', 'Effluent Treated')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit', models.CharField(help_text='e.g. kg, m³, litres, bags', max_length=30)),
                ('biogas_m3', models.DecimalField(decimal_places=3, default=0, help_text='Biogas volume if applicable', max_digits=10)),
                ('energy_kwh_equivalent', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('compost_batch_id', models.CharField(blank=True, max_length=100)),
                ('compost_maturity_days', models.PositiveSmallIntegerField(default=0)),
                ('record_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manure_biogas_records', to='enterprises.enterprise')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manure_biogas_records', to='accounts.organization')),
            ],
            options={
                'db_table': 'manure_biogas_records',
                'ordering': ['-record_date'],
            },
        ),
    ]
