# Generated by Django 5.1.4 on 2026-05-26 22:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('enterprises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('detail', models.TextField()),
                ('recommendation_type', models.CharField(choices=[('feeding', 'Feeding'), ('health', 'Health'), ('financial', 'Financial'), ('operational', 'Operational'), ('alert', 'Alert'), ('forecast', 'Forecast')], max_length=30)),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('impact', models.TextField(blank=True)),
                ('data_sources', models.JSONField(default=list)),
                ('is_actioned', models.BooleanField(default=False)),
                ('actioned_at', models.DateTimeField(blank=True, null=True)),
                ('model_version', models.CharField(blank=True, max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('actioned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actioned_recommendations', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_recommendations', to='enterprises.enterprisebatch')),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_recommendations', to='enterprises.enterprise')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to='accounts.organization')),
            ],
            options={
                'db_table': 'ai_recommendations',
                'ordering': ['-urgency', '-generated_at'],
            },
        ),
    ]
