# Generated by Django 5.1.4 on 2026-06-05 15:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('enterprises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag_number', models.CharField(max_length=100)),
                ('rfid_tag', models.CharField(blank=True, db_index=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('species', models.CharField(choices=[('cattle', 'Cattle'), ('sheep', 'Sheep'), ('goat', 'Goat'), ('pig', 'Pig'), ('chicken', 'Chicken'), ('duck', 'Duck'), ('other', 'Other')], default='cattle', max_length=20)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('castrated', 'Castrated Male')], default='female', max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_acquisition', models.DateField(blank=True, null=True)),
                ('acquisition_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('deceased', 'Deceased'), ('culled', 'Culled'), ('transferred', 'Transferred')], default='active', max_length=20)),
                ('current_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('target_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('markings', models.TextField(blank=True)),
                ('is_pregnant', models.BooleanField(default=False)),
                ('expected_delivery', models.DateField(blank=True, null=True)),
                ('dam_tag', models.CharField(blank=True, help_text='Mother tag number', max_length=100)),
                ('sire_tag', models.CharField(blank=True, help_text='Father tag number', max_length=100)),
                ('current_pen', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('photo_url', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animal_records', to='enterprises.enterprise')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_records', to='accounts.organization')),
            ],
            options={
                'db_table': 'animal_records',
                'ordering': ['tag_number'],
                'unique_together': {('organization', 'tag_number')},
            },
        ),
        migrations.CreateModel(
            name='AnimalHealthEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('vaccination', 'Vaccination'), ('treatment', 'Treatment'), ('deworming', 'Deworming'), ('diagnosis', 'Diagnosis'), ('injury', 'Injury'), ('surgery', 'Surgery'), ('checkup', 'Routine Checkup'), ('quarantine', 'Quarantine'), ('death', 'Death')], max_length=20)),
                ('severity', models.CharField(choices=[('none', 'None / Routine'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('critical', 'Critical')], default='none', max_length=20)),
                ('diagnosis', models.CharField(blank=True, max_length=255)),
                ('treatment', models.TextField(blank=True)),
                ('medication', models.CharField(blank=True, max_length=255)),
                ('dosage', models.CharField(blank=True, max_length=100)),
                ('withholding_days', models.PositiveSmallIntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vet_name', models.CharField(blank=True, max_length=255)),
                ('event_date', models.DateField()),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_events', to='tracking.animalrecord')),
            ],
            options={
                'db_table': 'animal_health_events',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='AnimalWeightEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('previous_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('gain_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('days_since_last', models.PositiveIntegerField(blank=True, null=True)),
                ('adg_kg', models.DecimalField(blank=True, decimal_places=4, help_text='Average daily gain', max_digits=6, null=True)),
                ('weigh_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_events', to='tracking.animalrecord')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
                ('weighed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'animal_weight_events',
                'ordering': ['-weigh_date'],
            },
        ),
        migrations.CreateModel(
            name='FeedingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pen', models.CharField(blank=True, help_text='Pen/group if not per-animal', max_length=100)),
                ('feed_type', models.CharField(max_length=255)),
                ('quantity_kg', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cost_per_kg', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dispensed_by', models.CharField(blank=True, help_text='Smart feeder ID or worker name', max_length=100)),
                ('feed_date', models.DateField()),
                ('feed_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeding_records', to='tracking.animalrecord')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            options={
                'db_table': 'feeding_records',
                'ordering': ['-feed_date', '-feed_time'],
            },
        ),
        migrations.CreateModel(
            name='HeatEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('detected_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('detected', 'Detected'), ('served', 'Served / Mated'), ('confirmed_pregnant', 'Confirmed Pregnant'), ('not_pregnant', 'Not In Calf')], default='detected', max_length=20)),
                ('detection_method', models.CharField(blank=True, help_text='RFID pedometer / visual / hormonal', max_length=100)),
                ('sire_used', models.CharField(blank=True, max_length=255)),
                ('service_date', models.DateField(blank=True, null=True)),
                ('expected_calving', models.DateField(blank=True, null=True)),
                ('is_ai', models.BooleanField(default=False, help_text='Artificial insemination')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heat_events', to='tracking.animalrecord')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            options={
                'db_table': 'heat_events',
                'ordering': ['-detected_at'],
            },
        ),
    ]
