# Generated by Django 5.1.4 on 2026-06-05 19:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('devices', '0001_initial'),
        ('enterprises', '0001_initial'),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoopDoor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('pen', models.CharField(blank=True, max_length=100)),
                ('control_mode', models.CharField(choices=[('schedule', 'Time Schedule'), ('light', 'Light Sensor'), ('manual', 'Manual Only')], default='schedule', max_length=20)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('open_light_lux', models.PositiveIntegerField(default=500, help_text='Open when light > this value')),
                ('close_light_lux', models.PositiveIntegerField(default=100, help_text='Close when light < this value')),
                ('is_open', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coop_doors', to='devices.device')),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coop_doors', to='enterprises.enterprise')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coop_doors', to='accounts.organization')),
            ],
            options={
                'db_table': 'coop_doors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CoopDoorEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('opened', 'Opened'), ('closed', 'Closed'), ('fault', 'Fault')], max_length=10)),
                ('trigger', models.CharField(choices=[('schedule', 'Schedule'), ('light_sensor', 'Light Sensor'), ('manual', 'Manual'), ('system', 'System Override')], default='schedule', max_length=20)),
                ('light_level_lux', models.PositiveIntegerField(blank=True, null=True)),
                ('fault_description', models.CharField(blank=True, max_length=255)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('door', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tracking.coopdoor')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            options={
                'db_table': 'coop_door_events',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='SmartFeeder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('pen', models.CharField(blank=True, max_length=100)),
                ('capacity_kg', models.DecimalField(decimal_places=2, default=50, max_digits=8)),
                ('current_level_pct', models.PositiveSmallIntegerField(default=100)),
                ('low_level_alert_pct', models.PositiveSmallIntegerField(default=20)),
                ('ration_per_dispense_kg', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('dispense_times', models.JSONField(default=list, help_text='["06:00","12:00","18:00"]')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smart_feeders', to='devices.device')),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smart_feeders', to='enterprises.enterprise')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_feeders', to='accounts.organization')),
            ],
            options={
                'db_table': 'smart_feeders',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeederDispenseEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_kg', models.DecimalField(decimal_places=3, max_digits=8)),
                ('trigger', models.CharField(choices=[('scheduled', 'Scheduled'), ('manual', 'Manual'), ('appetite_low', 'Low Appetite Alert')], default='scheduled', max_length=20)),
                ('level_before_pct', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('level_after_pct', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('consumption_kg', models.DecimalField(decimal_places=3, default=0, help_text='Measured since last dispense', max_digits=8)),
                ('is_appetite_alert', models.BooleanField(default=False)),
                ('dispensed_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
                ('feeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispense_events', to='tracking.smartfeeder')),
            ],
            options={
                'db_table': 'feeder_dispense_events',
                'ordering': ['-dispensed_at'],
            },
        ),
    ]
