# Generated by Django 5.1.4 on 2026-06-05 19:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('devices', '0001_initial'),
        ('enterprises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GreenhouseZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('zone_type', models.CharField(choices=[('greenhouse', 'Greenhouse'), ('polytunnel', 'Poly Tunnel'), ('shade_house', 'Shade House'), ('hydroponic', 'Hydroponic Unit'), ('mushroom', 'Mushroom House'), ('nursery', 'Nursery')], default='greenhouse', max_length=20)),
                ('area_m2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('crop_type', models.CharField(blank=True, max_length=100)),
                ('crop_stage', models.CharField(blank=True, max_length=100)),
                ('planting_date', models.DateField(blank=True, null=True)),
                ('expected_harvest_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='greenhouse_zones', to='devices.device')),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='greenhouse_zones', to='enterprises.enterprise')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='greenhouse_zones', to='accounts.organization')),
            ],
            options={
                'db_table': 'greenhouse_zones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FertigationSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('trigger', models.CharField(choices=[('scheduled', 'Time Schedule'), ('ec_sensor', 'EC Drop Trigger'), ('ph_sensor', 'pH Trigger'), ('manual', 'Manual')], default='scheduled', max_length=20)),
                ('ec_target_ms_cm', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('ph_target', models.DecimalField(decimal_places=2, default=6.0, max_digits=4)),
                ('ph_tolerance', models.DecimalField(decimal_places=2, default=0.3, max_digits=3)),
                ('volume_litres', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('duration_minutes', models.PositiveIntegerField(default=15)),
                ('nutrients', models.JSONField(default=dict, help_text='e.g. {"N": 150, "P": 50, "K": 200} ppm')),
                ('frequency', models.CharField(blank=True, help_text='e.g. Every 4 hours, 3x per day', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fertigation_schedules', to='greenhouse.greenhousezone')),
            ],
            options={
                'db_table': 'fertigation_schedules',
            },
        ),
        migrations.CreateModel(
            name='FertigationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ec_before', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ec_after', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ph_before', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('ph_after', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('water_temp_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('volume_litres', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('nutrients_used', models.JSONField(default=dict)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('is_alert', models.BooleanField(default=False)),
                ('alert_reason', models.CharField(blank=True, max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='greenhouse.fertigationschedule')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fertigation_events', to='greenhouse.greenhousezone')),
            ],
            options={
                'db_table': 'fertigation_events',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='ClimateTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('temp_min_c', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('temp_max_c', models.DecimalField(decimal_places=2, default=28, max_digits=5)),
                ('humidity_min_pct', models.PositiveSmallIntegerField(default=60)),
                ('humidity_max_pct', models.PositiveSmallIntegerField(default=85)),
                ('co2_min_ppm', models.PositiveIntegerField(default=400)),
                ('co2_max_ppm', models.PositiveIntegerField(default=1200)),
                ('light_min_lux', models.PositiveIntegerField(default=5000)),
                ('light_max_lux', models.PositiveIntegerField(default=50000)),
                ('vpd_min', models.DecimalField(decimal_places=2, default=0.8, max_digits=4)),
                ('vpd_max', models.DecimalField(decimal_places=2, default=1.6, max_digits=4)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='climate_target', to='greenhouse.greenhousezone')),
            ],
            options={
                'db_table': 'climate_targets',
            },
        ),
        migrations.CreateModel(
            name='ClimateReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('humidity_pct', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('co2_ppm', models.PositiveIntegerField(blank=True, null=True)),
                ('light_lux', models.PositiveIntegerField(blank=True, null=True)),
                ('vpd', models.DecimalField(blank=True, decimal_places=3, help_text='Vapour Pressure Deficit kPa', max_digits=5, null=True)),
                ('is_alert', models.BooleanField(default=False)),
                ('alert_details', models.JSONField(default=list, help_text='List of out-of-range parameters')),
                ('recorded_at', models.DateTimeField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climate_readings', to='greenhouse.greenhousezone')),
            ],
            options={
                'db_table': 'climate_readings',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='ClimateActuatorEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actuator_type', models.CharField(choices=[('fan', 'Extraction Fan'), ('vent', 'Roof Vent'), ('heater', 'Heater'), ('shade_net', 'Shade Net'), ('mister', 'Misting System'), ('co2_injector', 'CO₂ Injector'), ('grow_light', 'Grow Lights'), ('pump', 'Water/Nutrient Pump')], max_length=20)),
                ('action', models.CharField(choices=[('on', 'Turned On'), ('off', 'Turned Off'), ('set_pct', 'Set to %')], max_length=10)),
                ('trigger', models.CharField(choices=[('sensor', 'Sensor Triggered'), ('schedule', 'Scheduled'), ('manual', 'Manual Override'), ('forecast', 'Weather Forecast')], default='sensor', max_length=20)),
                ('value_pct', models.PositiveSmallIntegerField(blank=True, help_text='For set_pct action — 0-100', null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actuator_events', to='greenhouse.greenhousezone')),
            ],
            options={
                'db_table': 'climate_actuator_events',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='GrowLightSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('crop_stage', models.CharField(blank=True, max_length=100)),
                ('lights_on_time', models.TimeField()),
                ('lights_off_time', models.TimeField()),
                ('photoperiod_hours', models.DecimalField(decimal_places=1, default=16, max_digits=4)),
                ('intensity_pct', models.PositiveSmallIntegerField(default=100)),
                ('spectrum', models.CharField(blank=True, help_text='e.g. Full spectrum, Red/Blue only', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grow_light_schedules', to='greenhouse.greenhousezone')),
            ],
            options={
                'db_table': 'grow_light_schedules',
                'ordering': ['lights_on_time'],
            },
        ),
        migrations.CreateModel(
            name='HydroponicReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ec_ms_cm', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('ph', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('water_temp_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dissolved_oxygen_mg_l', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tank_level_pct', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_alert', models.BooleanField(default=False)),
                ('alert_details', models.JSONField(default=list)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hydroponic_readings', to='greenhouse.greenhousezone')),
            ],
            options={
                'db_table': 'hydroponic_readings',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
