# Generated by Django 5.1.4 on 2026-08-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_dde14f_idx',
            old_name='notif_recip_unread_idx',
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('alert', 'Alert'), ('automation', 'Automation'), ('weather', 'Weather'), ('kpi', 'KPI'), ('irrigation', 'Irrigation'), ('livestock', 'Livestock'), ('equipment', 'Equipment'), ('financial', 'Financial'), ('labor', 'Labour'), ('inventory', 'Inventory'), ('market', 'Market'), ('compliance', 'Compliance'), ('vision', 'AI Vision'), ('system', 'System'), ('video_call', 'Video Call')], default='system', max_length=30),
        ),
    ]
