# Generated by Django 5.1.4 on 2026-05-26 22:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=30)),
                ('production_type', models.CharField(max_length=100)),
                ('icon', models.CharField(default='leaf', max_length=100)),
                ('color', models.CharField(default='#2D5016', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('batch_unit', models.CharField(default='batch', max_length=50)),
                ('settings', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprises', to='accounts.organization')),
            ],
            options={
                'db_table': 'enterprises',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EnterpriseStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('stage_order', models.PositiveIntegerField(default=0)),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('color', models.CharField(default='#2D5016', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('feeding_rules', models.JSONField(default=list)),
                ('health_checks', models.JSONField(default=list)),
                ('kpi_targets', models.JSONField(default=list)),
                ('alerts', models.JSONField(default=list)),
                ('required_records', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='enterprises.enterprise')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            options={
                'db_table': 'enterprise_stages',
                'ordering': ['stage_order'],
            },
        ),
        migrations.CreateModel(
            name='EnterpriseBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit', models.CharField(default='units', max_length=50)),
                ('start_date', models.DateField()),
                ('expected_end_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='enterprises.enterprise')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
                ('current_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_batches', to='enterprises.enterprisestage')),
            ],
            options={
                'db_table': 'enterprise_batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnterpriseTemplate',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('livestock', 'Livestock'), ('aquaculture', 'Aquaculture'), ('crop', 'Crop'), ('horticulture', 'Horticulture'), ('dairy', 'Dairy'), ('apiculture', 'Apiculture'), ('mushroom', 'Mushroom'), ('hydroponics', 'Hydroponics'), ('greenhouse', 'Greenhouse'), ('processing', 'Processing'), ('mixed', 'Mixed'), ('custom', 'Custom')], max_length=30)),
                ('production_type', models.CharField(max_length=100)),
                ('icon', models.CharField(default='leaf', max_length=100)),
                ('color', models.CharField(default='#2D5016', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_built_in', models.BooleanField(default=False)),
                ('stages', models.JSONField(default=list)),
                ('kpis', models.JSONField(default=list)),
                ('forms', models.JSONField(default=list)),
                ('inventory_rules', models.JSONField(default=list)),
                ('financial_categories', models.JSONField(default=list)),
                ('automation_rules', models.JSONField(default=list)),
                ('dashboard_widgets', models.JSONField(default=list)),
                ('tags', models.JSONField(default=list)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_templates', to='accounts.organization')),
            ],
            options={
                'db_table': 'enterprise_templates',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='enterprise',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='enterprises.enterprisetemplate'),
        ),
    ]
