# Generated by Django 4.2.13 on 2026-09-02 00:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(choices=[('payment', 'Payment System'), ('notification', 'Notification Service'), ('gateway', 'Shared Gateway')], max_length=20, unique=True)),
                ('base_url', models.URLField(blank=True, help_text='e.g. https://payments.afriswip.com')),
                ('app_id', models.CharField(blank=True, help_text="Non-secret identifier for this app on the other side, e.g. Payment's app_id / NOTIF_APPLICATION_CODE", max_length=200)),
                ('encrypted_api_key', models.TextField(blank=True)),
                ('encrypted_secret', models.TextField(blank=True, help_text='For services needing a second value, e.g. a webhook secret')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_by', models.CharField(blank=True, default='', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Integration Credential',
                'verbose_name_plural': 'Integration Credentials',
                'db_table': 'integration_credentials',
            },
        ),
    ]
